function [equacoes] = gera_equacoes(item, dx, dt)
    
    equacoes = cell(0);
    dx2 = dx^2;
    
    if item == "ad"

        % Aij em um ponto no interior do domínio
        equacoes{end + 1} = @(A, j, i, mi, ~, Jz)...
            (A(j, i+1) + A(j, i-1) + A(j+1, i) + A(j - 1, i))/4 + dx2/4*mi*Jz;

        % Aij na fronteira vertical entre dois meios
        equacoes{end + 1} = @(A, j, i, mi1, ~, Jz1, mi2, ~, Jz2)...
            (2*(mi2*A(j,i-1) + mi1*A(j,i+1)) + (mi1 + mi2)*(A(j-1,i) + A(j+1,i))...
            + (mi1*mi2*dx2)*(Jz1 + Jz2))/(4*(mi1 + mi2));

        % Aij na fronteira horizontal entre dois meios
        equacoes{end + 1} = @(A, j, i, mi1, ~, Jz1, mi2, ~, Jz2) ...
            (2*(mi2*A(j-1,i) + mi1*A(j+1,i)) + (mi1 + mi2)*(A(j,i-1) + A(j,i+1))...
            + (mi1*mi2*dx2)*(Jz1 + Jz2))/(4*(mi1 + mi2));
        
    elseif item == "e1"
        % Aij um ponto no interior do domínio
        equacoes{end + 1} = @(A, j, i, mix, miy, Jz)...
            ((1/2).*(mix+miy).^(-1).*(dx2.*Jz.*mix.*miy+mix.*...
            (A(j,i-1)+A(j,i+1))+miy.*(A(j-1,i)+A(j+1,i))));

        % Aij na fronteira vertical entre dois meios
        equacoes{end + 1} = @(A, j, i, mix1, miy1, Jz1, mix2, miy2, Jz2)...
            ((1/2).*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*...
            (miy1+miy2))).^(-1).*(2.*mix1.*mix2.*miy1.*A(j,i+1)+miy2.*...
            (2.*mix1.*mix2.*A(j,i-1)+miy1.*(dx2.*(Jz1+Jz2).*...
            mix1.*mix2+(mix1+mix2).*A(j-1,i)+(mix1+mix2).*A(j+1,i)))));

        % Aij na fronteira horizontal entre dois meios
        equacoes{end + 1} = @(A, j, i, mix1, miy1, Jz1, mix2, miy2, Jz2) ...
            ((1/2).*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*...
            (miy1+miy2))).^(-1).*(mix1.*mix2.*(miy1+miy2).*A(j,i-1)+...
            mix1.*mix2.*(miy1+miy2).*A(j,i+1)+miy1.*miy2.*...
            (mix2.*(dx2.*(Jz1+Jz2).*mix1+2.*A(j-1,i))+2.*mix1.*A(j+1,i))));
                
    elseif item == "e2"

        % Em pontos da bobina %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Aij em um ponto no interior da bobina
        equacoes{end + 1} = @(A, j, i, k, t, mix, miy, Jz, sigma)...
        (dx.^(-2).*mix.^(-1).*miy.^(-1).*sigma.^(-1).*(dt.* ...
        miy.*(A((-1)+j,i,k)+(-2).*A(j,i,k)+A(1+j,i,k))+mix.*(dt.*(A(j,(-1) ...
        +i,k)+(-2).*A(j,i,k)+A(j,1+i,k))+dx2.*miy.*(sigma.*A(j,i,k)+dt.* ...
        Jz.*cos(60.*t)))));

        % Aij na fronteira vertical da bobina
        equacoes{end + 1} = @(A, j, i, k, t, mix1, miy1, Jz1, mix2, ...
            miy2, Jz2, sigma1, sigma2)...
        (dx.^(-2).*mix1.^(-1).*mix2.^(-1).*miy1.^(-1).* ...
        miy2.^(-1).*(sigma1+sigma2).^(-1).*(((-2).*dt.*mix2.*miy1.*miy2+ ...
        mix1.*((-2).*dt.*miy1.*miy2+mix2.*((-2).*dt.*miy2+miy1.*((-2).*dt+ ...
        dx2.*miy2.*(sigma1+sigma2))))).*A(j,i,k)+dt.*(2.*mix1.*mix2.* ...
        miy1.*A(j,1+i,k)+miy2.*(2.*mix1.*mix2.*A(j,(-1)+i,k)+miy1.*((mix1+ ...
        mix2).*A((-1)+j,i,k)+(mix1+mix2).*A(1+j,i,k)+dx2.*(Jz1+Jz2).* ...
        mix1.*mix2.*cos(60.*t))))));

        % Aij na fronteira horizontal da bobina
        equacoes{end + 1} = @(A, j, i, k, t, mix1, miy1, Jz1, mix2, ...
            miy2, Jz2, sigma1, sigma2) ...
        (dx.^(-2).*mix1.^(-1).*mix2.^(-1).*miy1.^(-1).* ...
        miy2.^(-1).*(sigma1+sigma2).^(-1).*(dt.*mix1.*mix2.*(miy1+miy2).* ...
        A(j,(-1)+i,k)+((-2).*dt.*mix2.*miy1.*miy2+mix1.*((-2).*dt.*miy1.* ...
        miy2+mix2.*((-2).*dt.*miy2+miy1.*((-2).*dt+dx2.*miy2.*(sigma1+ ...
        sigma2))))).*A(j,i,k)+dt.*(mix1.*mix2.*(miy1+miy2).*A(j,1+i,k)+ ...
        miy1.*miy2.*(2.*mix1.*A(1+j,i,k)+mix2.*(2.*A((-1)+j,i,k)+dx2.*( ...
        Jz1+Jz2).*mix1.*cos(60.*t))))));
    
        % Em pontos interiores fora da bobina %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        
        % À esquerda da bobina
        equacoes{end + 1} = @(A, j, i, k, mix, miy)...
        (A(j,(-1)+i,1+k))==(2.*A(j,i,1+k)+(-1).*A(j,1+i,1+k)+(-1).*mix.^( ...
        -1).*miy.*(A((-1)+j,i,1+k)+(-2).*A(j,i,1+k)+A(1+j,i,1+k)));

        % À direita da bobina
        equacoes{end + 1} = @(A, j, i, k, mix, miy)...
        ((-1).*A(j,(-1)+i,1+k)+2.*A(j,i,1+k)+(-1).*mix.^( ...
        -1).*miy.*(A((-1)+j,i,1+k)+(-2).*A(j,i,1+k)+A(1+j,i,1+k)));

        % Abaixo
        equacoes{end + 1} = @(A, j, i, k, mix, miy)...
        (2.*A(j,i,1+k)+(-1).*mix.*miy.^(-1).*(A(j,(-1)+ ...
        i,1+k)+(-2).*A(j,i,1+k)+A(j,1+i,1+k))+(-1).*A(1+j,i,1+k));

        % Acima
        equacoes{end + 1} = @(A, j, i, k, mix, miy)...
        ((-1).*A((-1)+j,i,1+k)+2.*A(j,i,1+k)+(-1).*mix.* ...
        miy.^(-1).*(A(j,(-1)+i,1+k)+(-2).*A(j,i,1+k)+A(j,1+i,1+k)));
    
        % Em fronteiras verticais fora da bobina %%%%%%%%%%%%%%%%%%%%%%%%%%
        
        % Esquerdo
        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        ((1/2).*mix1.^(-1).*mix2.^(-1).*miy2.^(-1).*( ...
        2.*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*(miy1+miy2))).*A(j,i, ...
        1+k)+(-1).*miy1.*(2.*mix1.*mix2.*A(j,1+i,1+k)+(mix1+mix2).*miy2.*( ...
        A((-1)+j,i,1+k)+A(1+j,i,1+k)))));

        % Direito
        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        ((1/2).*mix1.^(-1).*mix2.^(-1).*miy1.^(-1).*(2.*( ...
        mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*(miy1+miy2))).*A(j,i,1+k) ...
        +(-1).*miy2.*(2.*mix1.*mix2.*A(j,(-1)+i,1+k)+(mix1+mix2).*miy1.*( ...
        A((-1)+j,i,1+k)+A(1+j,i,1+k)))));

        % Baixo
        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        ((mix1+mix2).^(-1).*miy1.^(-1).*miy2.^(-1).*( ...
        2.*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*(miy1+miy2))).*A(j,i, ...
        1+k)+(-2).*mix1.*mix2.*miy1.*A(j,1+i,1+k)+(-1).*miy2.*(2.*mix1.* ...
        mix2.*A(j,(-1)+i,1+k)+(mix1+mix2).*miy1.*A(1+j,i,1+k))));
    
        % Cima
        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        ((mix1+mix2).^(-1).*miy1.^(-1).*miy2.^(-1).*((-1) ...
        .*miy2.*((mix1+mix2).*miy1.*A((-1)+j,i,1+k)+2.*mix1.*mix2.*A(j,( ...
        -1)+i,1+k))+2.*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*(miy1+ ...
        miy2))).*A(j,i,1+k)+(-2).*mix1.*mix2.*miy1.*A(j,1+i,1+k)));
        
         % Em fronteiras horizontais fora da bobina %%%%%%%%%%%%%%%%%%%%%%%

        % Esquerdo

        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        (mix1.^(-1).*mix2.^(-1).*(miy1+miy2).^(-1).*( ...
        2.*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*(miy1+miy2))).*A(j,i, ...
        1+k)+(-1).*mix1.*mix2.*(miy1+miy2).*A(j,1+i,1+k)+(-2).*miy1.* ...
        miy2.*(mix2.*A((-1)+j,i,1+k)+mix1.*A(1+j,i,1+k))));

        % Direito 
        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        (mix1.^(-1).*mix2.^(-1).*(miy1+miy2).^(-1).*((-1) ...
        .*mix1.*mix2.*(miy1+miy2).*A(j,(-1)+i,1+k)+2.*(mix2.*miy1.*miy2+ ...
        mix1.*(miy1.*miy2+mix2.*(miy1+miy2))).*A(j,i,1+k)+(-2).*miy1.* ...
        miy2.*(mix2.*A((-1)+j,i,1+k)+mix1.*A(1+j,i,1+k))));

        % Baixo
        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        ((-1/2).*mix2.^(-1).*miy1.^(-1).*miy2.^(-1).*( ...
        mix1.*mix2.*(miy1+miy2).*A(j,(-1)+i,1+k)+(-2).*(mix2.*miy1.*miy2+ ...
        mix1.*(miy1.*miy2+mix2.*(miy1+miy2))).*A(j,i,1+k)+mix1.*(mix2.*( ...
        miy1+miy2).*A(j,1+i,1+k)+2.*miy1.*miy2.*A(1+j,i,1+k))));

        % Cima
        equacoes{end + 1} = @(A, j, i, mix1, miy1, mix2, miy2)...
        ((-1/2).*mix1.^(-1).*miy1.^(-1).*miy2.^(-1).*( ...
        mix1.*mix2.*(miy1+miy2).*A(j,(-1)+i,1+k)+(-2).*(mix2.*miy1.*miy2+ ...
        mix1.*(miy1.*miy2+mix2.*(miy1+miy2))).*A(j,i,1+k)+mix2.*(2.*miy1.* ...
        miy2.*A((-1)+j,i,1+k)+mix1.*(miy1+miy2).*A(j,1+i,1+k))));

    
    end

end

