function [varargout] = gera_equacoes(item, dx)
    
    varargout = {0, 0 ,0};
    dx2 = dx^2;
    if item == "ad"

        % Função de cálculo de Aij em um ponto no interior do domínio
        Aij_interior = @(A, j, i, mi, ~, Jz)...
            (A(j, i+1) + A(j, i-1) + A(j+1, i) + A(j - 1, i))/4 + dx2/4*mi*Jz;

        % Função de cálculo de Aij na fronteira vertical entre dois meios
        Aij_front_vert = @(A, j, i, mi1, ~, Jz1, mi2, ~, Jz2)...
            (2*(mi2*A(j,i-1) + mi1*A(j,i+1)) + (mi1 + mi2)*(A(j-1,i) + A(j+1,i))...
            + (mi1*mi2*dx2)*(Jz1 + Jz2))/(4*(mi1 + mi2));

        % Função de cálculo de Aij na fronteira horizontal entre dois meios
        Aij_front_hori = @(A, j, i, mi1, ~, Jz1, mi2, ~, Jz2) ...
            (2*(mi2*A(j-1,i) + mi1*A(j+1,i)) + (mi1 + mi2)*(A(j,i-1) + A(j,i+1))...
            + (mi1*mi2*dx2)*(Jz1 + Jz2))/(4*(mi1 + mi2));
    
        i = 1;
        for arg={Aij_interior, Aij_front_vert, Aij_front_hori}
            varargout{i} = arg{1};
            i = i + 1;
        end
        
    elseif item == "e1"
        % Função de cálculo de Aij com mi diferente em x e y em um ponto no interior do domínio
        Aij_2mis_interior = @(A, j, i, mix, miy, Jz)...
            ((1/2).*(mix+miy).^(-1).*(dx2.*Jz.*mix.*miy+mix.*...
            (A(j,i-1)+A(j,i+1))+miy.*(A(j-1,i)+A(j+1,i))));

        % Função de cálculo de Aij com mi diferente em x e y na fronteira vertical entre dois meios
        Aij_2mis_front_vert = @(A, j, i, mix1, miy1, Jz1, mix2, miy2, Jz2)...
            ((1/2).*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*...
            (miy1+miy2))).^(-1).*(2.*mix1.*mix2.*miy1.*A(j,i+1)+miy2.*...
            (2.*mix1.*mix2.*A(j,i-1)+miy1.*(dx2.*(Jz1+Jz2).*...
            mix1.*mix2+(mix1+mix2).*A(j-1,i)+(mix1+mix2).*A(j+1,i)))));

        % Função de cálculo de Aij com mi diferente em x e y na fronteira horizontal entre dois meios
        Aij_2mis_front_hori = @(A, j, i, mix1, miy1, Jz1, mix2, miy2, Jz2) ...
            ((1/2).*(mix2.*miy1.*miy2+mix1.*(miy1.*miy2+mix2.*...
            (miy1+miy2))).^(-1).*(mix1.*mix2.*(miy1+miy2).*A(j,i-1)+...
            mix1.*mix2.*(miy1+miy2).*A(j,i+1)+miy1.*miy2.*...
            (mix2.*(dx2.*(Jz1+Jz2).*mix1+2.*A(j-1,i))+2.*mix1.*A(j+1,i))));
        
        i = 1;
        for arg={Aij_2mis_interior, Aij_2mis_front_vert, Aij_2mis_front_hori}
            varargout{i} = arg{1};
            i = i + 1;
        end
        
    elseif item == "e2"
        dt = 0.0001; % Passo no tempo

        % Função de cálculo de Aij com mi diferente em x e y em um ponto no interior do domínio
        Aijkmais1_interior = @(A, j, i, k, t, mix, miy, Jz, sigma)...
            (dx.^(-2).*mix.^(-1).*miy.^(-1).*sigma.^(-1).*(dt.*miy.* ...
            (A(j-1,i,k)+(-2).*A(j,i,k)+A(j+1,i,k))+mix.* ...
            (dt.*(A(j,i-1,k)+(-2).*A(j,i,k)+A(j,i+1,k))+dx2.*miy.* ...
            (sigma.*A(j,i,k)+dt.*Jz.*cos(60.*t)))));

        % Função de cálculo de Aij com mi diferente em x e y na fronteira vertical entre dois meios
        Aijkmais1_front_vert = @(A, j, i, k, t, mix1, miy1, Jz1, mix2, miy2, Jz2, sigma1, sigma2)...
            ((1/2).*dx.^(-2).*mix1.^(-1).*mix2.^(-1).*miy1.^(-1).* ...
            miy2.^(-1).*sigma.^(-1).*((-2).*(dt.*mix2.*miy1.*miy2+mix1.* ...
            (dt.*miy1.*miy2+mix2.*(dt.*miy2+miy1.*(dt+(-1).*dx2.*miy2.*sigma)))).* ...
            A(j,i,k)+dt.*(2.*mix1.*mix2.*miy1.*A(j,i+1,k)+miy2.* ...
            (2.*mix1.*mix2.*A(j,i-1,k)+miy1.*((mix1+mix2).* ...
            A(j-1,i,k)+(mix1+mix2).*A(j+1,i,k)+dx2.* ...
            (Jz1+Jz2).*mix1.*mix2.*cos(60.*t))))));

        % Função de cálculo de Aij com mi diferente em x e y na fronteira horizontal entre dois meios
        Aijkmais1_front_hori = @(A, j, i, k, t, mix1, miy1, Jz1, mix2, miy2, Jz2, sigma1, sigma2) ...
            ((1/2).*dx.^(-2).*mix1.^(-1).*mix2.^(-1).*miy1.^(-1).* ...
            miy2.^(-1).*sigma.^(-1).*(dt.*mix1.*mix2.*(miy1+miy2).* ...
            A(j,i-1,k)+(-2).*(dt.*mix2.*miy1.*miy2+mix1.* ...
            (dt.*miy1.*miy2+mix2.*(dt.*miy2+miy1.* ...
            (dt+(-1).*dx2.*miy2.*sigma)))).*A(j,i,k)+dt.* ...
            (mix1.*mix2.*(miy1+miy2).*A(j,i+1,k)+miy1.*miy2.* ...
            (2.*mix1.*A(j+1,i,k)+mix2.*(2.*A(j-1,i,k)+dx2.* ...
            (Jz1+Jz2).*mix1.*cos(60.*t))))));
    
            i = 1;
        for arg={Aijkmais1_interior, Aijkmais1_front_vert, Aijkmais1_front_hori}
            varargout{i} = arg{1};
            i = i + 1;
        end
        
    end

end

